---

- name: run whoami
  command: whoami
  changed_when: false
  check_mode: false
  register: whoami

- name: install Development Tools
  yum:
    name: "@Development Tools"
  become: true

- name: install build dependencies
  yum:
    name:
      - gtk+-devel
      - gtk3-devel
      - libXpm-devel
      - libpng-devel
      - giflib-devel
      - libtiff-devel
      - libjpeg-devel
      - ncurses-devel
      - gpm-devel
      - dbus-devel
      - dbus-glib-devel
      - dbus-python
      - GConf2-devel
      - pkgconfig
      - libXft-devel
      - libxml2-devel
      - gnutls-devel
      - jasper-devel
      - libgs-devel
      - ImageMagick-devel
      - lcms2-devel
      - gpm-devel
      - librsvg2-devel
      - m17n-lib-devel
      - libacl-devel
      - Xaw3d-devel
  become: true
  notify: configure

- name: check if directory to store Emacs source code exists
  stat:
    path: "{{ source_dir }}"
  become: true
  register: stat_source_dir

- name: make sure directory to store Emacs source code exists
  file:
    group: "{{ whoami.stdout }}"
    mode: 0775
    owner: "{{ whoami.stdout }}"
    path: "{{ source_dir }}"
    state: directory
  become: true
  when: not stat_source_dir.stat.exists

- name: download source code
  unarchive:
    creates: "{{ source_dir }}/emacs-{{ version }}"
    dest: "{{ source_dir }}"
    group: "{{ whoami.stdout }}"
    owner: "{{ whoami.stdout }}"
    remote_src: true
    src: https://ftp.gnu.org/pub/gnu/emacs/emacs-{{ version }}.tar.xz
  become: true
  notify: configure

- name: create directory for Emacs config files
  file:
    group: "{{ config_group }}"
    mode: 0700
    owner: "{{ config_owner }}"
    path: "{{ config_dir }}"
    state: directory
  become: true

- name: download init.el file
  get_url:
    dest:  "{{ config_dir }}"
    group: "{{ config_group }}"
    mode:  0664
    owner: "{{ config_owner }}"
    url:   "{{ config_url_init }}"
  become: true

- name: download custom.el file
  get_url:
    dest:  "{{ config_dir }}"
    group: "{{ config_group }}"
    mode:  0664
    owner: "{{ config_owner }}"
    url:   "{{ config_url_custom }}"
  become: true
